#Code to estimate time of thermal emergence
setwd("C:/Users/StortiniC/Desktop/Shaylyn/Code/MAR_thermal_emerg")

library(dplyr)
require(plyr)
require(data.table)

extract_fls <- list.files("output/climate_extracts/", full.names=T)
extract_fls <- extract_fls[!grepl("shape",extract_fls)] #there aer some additional shape files that aren't needed

mmfun<-function(d){ #this is a function to calculate max temp per year
  max<-data.frame(maxT=max(d$temp,na.rm=TRUE))
  return(max)
}

l<-list()
for(i in 1:length(extract_fls)){
  load(extract_fls[i]) #load in the cmip_extracts from a model run (generated by climate_extract.R)
  dat <- do.call("rbind",cmip_extracts) #turn the RData files into 2D dataframes 
  dvel<-ddply(dat,.(species,NAME,STATUS,TYPE,obis_count,site_area,cell_area,mod,climate_proj,year),.fun=mmfun,.progress='text')
  l[[i]]<-dvel
  } # This will take a while (~30min)... many files to loop through.
 max<-data.frame(rbindlist(l))

## Now merge with species list to get upper thermal limit for each species
spp<-read.csv("data/species_niche_final.csv")
names(spp)
spp$species=spp$SciName
names(spp)
spp<-spp[,c(4,9)]
df<-merge(max,spp,by="species")
names(df)
write.csv(df,"output/maxt_timeseries/maxt_timeseries.csv")

##############################################################
findToE<-function(d){
  
  ##IF SPECIES DOES NOT EMERGE FROM ITS NICHE BY END OF PROJECTION, SET TO THIS
  ToEFirst<-max(d$year)+1
  
  emYears<-which(d$maxT>d$UprTemp90)
  
  if(length(emYears)>0){
    
    x<-rep(0,length(d$year)) # create binary vector showing emergent (1) or non-emergent (0) years
    x[emYears]<-1
    
    #calculate the year when the temperature emerges for a period of at least 'runLength' years
    diffs <- x[-1L] != x[-length(x)] # find where the values change
    idx <- c(which(diffs), length(x)) # get the indexes, and then get the difference in subsequent indexes
    runs<-diff(c(0, idx))# calculate the length of the runs
    x2<-x[-which(c(NA,diff(x))==0)] # determine whether each run is a run of 1's or 0's
    yearsRunStart<-d$year[-which(c(NA,diff(x))==0)] # find the start year of each run
    runsTab<-data.frame(year=yearsRunStart,val=x2,run=runs) # store all this in a table
    runsTab<-runsTab[runsTab$val==1,] # remove runs of 0's
    runStart<-which(runsTab$run>=2) #find where temp>maxtolerance for 2 years in a row
    if(length(runStart)>0){
      ToEFirst<-min(runsTab$year[runStart]) #find the first year where there is a run of 1's equal to or greater than runLength
    }
    
  }
  return(ToEFirst)
}


## Get ToE for each model in each cell
ToEs<-ddply(df,.(species,NAME,STATUS,TYPE,obis_count,site_area,cell_area,mod,climate_proj),.fun=findToE,.progress='text')
head(ToEs)
ToEs$ToE<-ToEs$V1 #name the output "ToE" instead of V1
names(ToEs)
ToEs<-ToEs[,-10] #remove column names V1 (replaced with ToE)

#save final output
if(!dir.exists("output/ToEs/")){dir.create("output/ToEs/")}
write.csv(ToEs,"output/ToEs/ToEs_cells_allspp&models.csv")

