#Run a sensitivity analysis for mean vs max for each species. 

#load libraries -----
library(dplyr)
library(ggplot2)

#read in species niches
niche<-read.csv("data/species_niche_final.csv")


#extract annual means (only do this once by uncommenting the following text to the next code break)

    # #List of climate model outputs
    # extract_fls <- list.files("output/climate_extracts/", full.names=T)
    # extract_fls <- extract_fls[!grepl("shape",extract_fls)] #there aer some additional shape files that aren't needed
    # extract_fls <- extract_fls[!grepl("CNRM",extract_fls)] #the CNRM model was duplicated from GFDL
    # 
    # #create output directory
    # if(!dir.exists("output/cmip_yearly_averages/")){dir.create("output/cmip_yearly_averages/")}
    # 
    # for(i in extract_fls){
    # 
    #   #Get the data together
    #   load(i) #load in the cmip_extracts from a model run (generated by climate_extract.R)
    #   dat <- do.call("rbind",cmip_extracts)%>%  #stack it in a dataframe
    #                     group_by(species,NAME,year,month)%>% #unique cell ids
    #                     mutate(id=1:n())%>%
    #                     ungroup()%>%
    #                     data.frame()
    # 
    #   #progress message
    #   mod <- unique(dat$mod)
    #   climate_proj <- unique(dat$climate_proj)
    # 
    #   message(paste0("Working on ",mod," ",climate_proj))

    # #   #get the monthly average per grid cell (id)
    #   dat_ave <- dat%>%
    #              group_by(species,NAME,year,id)%>%
    #              summarise(temp=mean(temp,na.rm=T))%>%
    #              ungroup()%>%
    #              left_join(.,dat%>%
    #                          filter(month==1)%>% #because the months are repeated
    #                          dplyr::select(species,NAME,year,id,STATUS,
    #                                        TYPE,obis_count,site_area,cell_area))%>%
    #              mutate(mod=mod,
    #                     climate_proj=climate_proj)%>%
    #              dplyr::select(mod,climate_proj,species,year,NAME,id,STATUS,TYPE,obis_count,site_area,cell_area,temp)%>%
    #             suppressMessages()
    # 
    # 
    # dat_max <- dat%>%
    #             group_by(species,NAME,year,id)%>%
    #             summarise(temp=max(temp,na.rm=T))%>%
    #             ungroup()%>%
    #             left_join(.,dat%>%
    #                         filter(month==1)%>% #because the months are repeated
    #                         dplyr::select(species,NAME,year,id,STATUS,
    #                                       TYPE,obis_count,site_area,cell_area))%>%
    #             mutate(mod=mod,
    #                    climate_proj=climate_proj)%>%
    #             dplyr::select(mod,climate_proj,species,year,NAME,id,STATUS,TYPE,obis_count,site_area,cell_area,temp)%>%
    #             suppressMessages()
    #   
    #   
    #   #save the intermediate steps
    #  save(dat_ave,file=paste0("output/cmip_yearly_averages/",mod,"_",climate_proj,"_annual_temp_summaries.RData"))
    #  save(dat_max,file=paste0("output/cmip_yearly_averages/",mod,"_",climate_proj,"_annual_max_temp_summaries.RData"))
    #   
    #   rm(dat,dat_max,mod,climate_proj,dat_ave) #clean up the loop so that nothing is accidentally repeated (though this technically can't happen)
    #   
     } #end i loop, takes around 


#Load the data back in and format it for plotting
annual_mean_extracts <- list.files("output/cmip_yearly_averages/", full.names=T)
annual_mean_extracts <- annual_mean_extracts[!grepl("max",annual_mean_extracts)]
annual_max_extracts <- list.files("output/cmip_yearly_averages/", full.names=T)
annual_max_extracts <- setdiff(annual_max_extracts,annual_mean_extracts)


annual_dat_mean <- NULL
annual_dat_max <- NULL
for(i in 1:length(annual_mean_extracts)){
  
  load(annual_mean_extracts[i])
  load(annual_max_extracts[i])
  
  annual_dat_mean <- rbind(annual_dat_mean,dat_ave)
  annual_dat_max <- rbind(annual_dat_max,dat_max)
  
  rm(dat_ave,dat_max)
  
}


#Run a sensitivity analysis for comparing 'max' and 'mean' extractions for each species

species <- unique(annual_dat_mean$species)

if(!dir.exists("output/sensitivity_analyses/")){dir.create("output/sensitivity_analyses/")}

plot_list <- list() #this is for writing a pdf (which works but is a pain to look at)

for(i in species){
  
  message(paste0("Working on ",i))

test_sp <- i

test_dat <- rbind(annual_dat_mean%>%
                   filter(species==test_sp)%>%
                    mutate(var="mean"),
                  annual_dat_max%>%
                    filter(species==test_sp)%>%
                      mutate(var="max"))%>%
            mutate(climate_proj = paste0("RCP ",gsub("-",".",climate_proj)))

test_means <- test_dat%>%
              group_by(climate_proj,var,year,NAME,id)%>% #average of the models
              summarise(temp=mean(temp,na.rm=T))%>%
              ungroup()%>%
              group_by(climate_proj,var,year,NAME)%>% #average of the grid cells within site
              summarise(temp=mean(temp,na.rm=T))%>%
              ungroup()%>%
              group_by(climate_proj,var,year)%>% #average of the sites
              summarise(mean=mean(temp,na.rm=T))%>%    
              ungroup()%>%
              data.frame()%>%
              suppressMessages()

p1 <- ggplot()+
                  geom_line(data=test_dat,aes(x=year,y=temp,group=interaction(NAME,id)),lwd=0.5,col="grey50",alpha=0.5)+
                  geom_line(data=test_means,aes(x=year,y=mean),col="black")+
                  geom_hline(yintercept = niche%>%filter(SciName==test_sp)%>%pull(UprTemp90),
                             lwd=1.15,col="grey10",lty=6)+
                  theme_bw()+
                  theme(legend.position="none")+
                  labs(x="Year",y=expression("Temperature " ( degree*C)),title=i)+
                        facet_grid(var~climate_proj)

plot_list[[i]] <- p1

ggsave(paste0("output/sensitivity_analyses/sensitivity_analysis_",gsub(" ","_",i),".png"),p1,
       width=6,height=6,dpi=300,units="in")

}

#save it to a pdf -- note this isn't flattened so it is really slow to look at but all the images are in one pdf

pdf("output/sensitivity_analyses/sensitivity_analysis.pdf",onefile = TRUE) ##* note this is big and so isn't tracked by github. 
  for(i in species){print(plot_list[[i]])}
dev.off()
