## Plot temperature 2025, 2050, 2075, 2100 for sites

#load libraries -----
library(dplyr)
library(tidyr)

#List of climate model outputs
extract_fls <- list.files("output/climate_extracts/", full.names=T)
extract_fls <- extract_fls[!grepl("shape",extract_fls)] #there aer some additional shape files that aren't needed
extract_fls <- extract_fls[!grepl("CNRM",extract_fls)] #the CNRM model was duplicated from GFDL
extract_fls <- extract_fls[!grepl("GFDL",extract_fls)] #the CNRM model was duplicated from GFDL

#Create directory (if needed) for the toe_summaries
if(!dir.exists("output/temps/")){dir.create("output/temps/")}

#calculate the summary outputs
temps<-NULL

for(i in extract_fls){
  
  #Get the data together
  load(i) #load in the cmip_extracts from a model run (generated by climate_extract.R)
  dat <- do.call("rbind",cmip_extracts) #stack it in a dataframe
  
  #progress message
  mod <- unique(dat$mod)
  site<-unique(dat$NAME)
  climate_proj <- unique(dat$climate_proj)
  
  message(paste0("Working on ",mod,site," ",climate_proj))
  
  #Modify to include a grid cell ID
  dat2 <- dat%>%
    group_by(NAME,year,month)%>%
    mutate(id=1:n())%>% #this is a unique id for each 'cell' categorized within each site (NAME) and year
    ungroup()%>%
    data.frame()%>%
    left_join(.,dat)%>% #brings in the columns lost by group_by()
    suppressMessages() #just the joins and are not required 
  
  #save the intermediate steps
  save(dat2,file=paste0("output/temp_summaries/",mod,"_",climate_proj,"_temp_summaries.RData"))
  
  timeseries<-rbind(timeseries,dat2)
  
  rm(dat,mod,climate_proj) #clean up the loop so that nothing is accidentally repeated (though this technically can't happen)
  
} #end i loop, takes around 

#save for fast loading
save(toe_summaries,file=paste0("output/toe_summaries/all_toe_summaries.RData"))
save(timeseries,file=paste0("output/timeseries.RData"))

## Species by site loss for benchmark years  --------------------------------------
### WILL MANIPULATE THIS CODE TO MAKE SAME PLOT BUT FOR TEMP AT BENCHMARK YEARS INSTEAD OF SPECIES LOST
## NEED to see if the data we need is inside of timesries.RData
benchmark_years <- c(2025,2050,2075,2100)


species_lost_benchmark <- NULL
for(i in benchmark_years){
  
  species_lost_benchmark <- rbind(species_lost_benchmark,
                                  
                                  habitat_loss_site%>%
                                    filter(ToE != 2500, #these are species that did not emerge
                                           !species%in%c("Sebastes mentella","Calanus glacialis"),
                                           cum_sum==1,
                                           ToE<=i)%>%
                                    group_by(climate_proj,mod,NAME)%>%
                                    summarise(count=n())%>%
                                    ungroup()%>%
                                    left_join(.,species_count)%>%
                                    mutate(prop_lost = count/n_species,
                                           benchmark=i)%>%
                                    data.frame()
                                  
  )#end of loop growing dataframe
}

##make the data for plotting

benchmark_buffer  <-  rbind(site_dummy,site_dummy,site_dummy,site_dummy)%>% # four times, on dummy dataframe for each benchmark year
  mutate(benchmark = rep(benchmark_years,each=nrow(site_dummy)),
         max=NA,
         min=NA,
         comp=0,
         id=paste(climate_proj,NAME,benchmark,sep="-"))


plot_benchmark_formatted <- species_lost_benchmark%>%
  group_by(climate_proj,NAME,benchmark)%>%
  summarise(max=max(prop_lost,na.rm=T), #min among models
            min=min(prop_lost,na..rm=T), #max among models
            comp=prop_lost[mod == "Ensemble"])%>%
  ungroup()%>%
  mutate(id=paste(climate_proj,NAME,benchmark,sep="-"))%>%
  left_join(.,site_names)%>%
  left_join(.,network_cents%>%select(NAME,region,long))%>%
  dplyr::select(names(benchmark_buffer)) #line up the rows for the rbind() next


plot_benchmark_formatted <- rbind(plot_benchmark_formatted,
                                  benchmark_buffer%>%
                                    filter(id %in% setdiff(benchmark_buffer$id,plot_benchmark_formatted$id)))%>%
  mutate(facet_lab = ifelse(climate_proj == "2-6","RCP 2.6","RCP 8.5"),
         NAME = factor(NAME,levels=.[]%>%filter(climate_proj == "8-5",benchmark==2100)%>%arrange(region,comp)%>%pull(NAME)),
         abbreviation = factor(abbreviation,levels=.[]%>%filter(climate_proj == "8-5",benchmark==2100)%>%arrange(region,comp)%>%pull(abbreviation)))%>%
  data.frame()


benchmark_plot <-  ggplot(,aes(x=comp,y=abbreviation,fill=factor(benchmark)))+
  geom_bar(data=plot_benchmark_formatted%>%filter(benchmark==2100),stat="identity",col="black")+
  geom_bar(data=plot_benchmark_formatted%>%filter(benchmark==2075),stat="identity",col="black")+
  geom_bar(data=plot_benchmark_formatted%>%filter(benchmark==2050),stat="identity",col="black")+
  geom_bar(data=plot_benchmark_formatted%>%filter(benchmark==2025),stat="identity",col="black")+
  facet_grid(region~facet_lab,space="free_y",scales="free_y")+
  theme_bw()+
  labs(x="Lost species",y="",fill="")+
  scale_x_continuous(labels=percent,breaks=c(0,0.25,0.5,0.75),limits = c(0,round(max(plot_benchmark_formatted$comp),1)),expand=c(0,0))+
  theme(legend.position = "bottom",
        strip.text.y = element_text(size=6),
        axis.text.x = element_text(size=6))+
  scale_fill_viridis(discrete=T); benchmark_plot

ggsave("output/ENSEMBLE_benchmark_species_lost.png",benchmark_plot,width=9,height=6,units="in",dpi=300)

